# Generated by Django 3.1.5 on 2022-02-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkySoldier', '0002_auto_20220222_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazilarmodel',
            name='ozet',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
